apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: flask-calculator
        image: muthusurya/python-app:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: my-python-app
spec:
  type: NodePort
  selector:
    app: devops
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007
