apiVersion: v1
kind: Pod
metadata:
  name: python-app-pod
  labels:
    app: devops
spec:
  containers:
  - name: python-firstandlastname
    image: saran1910/python-sample:v1
    ports:
    - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: my-python-app
spec:
  type: NodePort
  selector:
    app: devops
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007
